#!/bin/bash
basename=$(basename "$1" '.lytex')
lilypond-book -I /home/theophile/Desktop/Music/supplement/includes/book/ --pdf --output=Supplement "$1"
cd Supplement
pdflatex $basename
pdflatex $basename
makeindex -s ../songs.ist ${basename}.idx
pdflatex $basename
pdflatex $basename
pdftk A=../../images/cover2.pdf B=${basename}.pdf cat A1 B2-end output ../${basename}.pdf
